# Generated by Django 2.1.7 on 2019-03-29 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_post_answer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='questions.Post'),
            preserve_default=False,
        ),
    ]
