# Generated by Django 2.1.7 on 2019-03-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20190331_1324'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE"
            + " ON questions_post FOR EACH ROW EXECUTE PROCEDURE"
            + " tsvector_update_trigger(search_vector, 'pg_catalog.english', title, body);"
        )
    ]
