# Generated by Django 2.1.7 on 2019-03-31 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20190331_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
